name: 'Filenames linter'
description: 'A Github Action to validate filenames using regular expressions.'
branding:
  icon: 'folder'
  color: white
inputs:
  path:
    description: 'The path to a directory to check the filenames.'
    required: true
    default: './'
  pattern:
    description: 'The regex pattern to match for each of the files in the given directory'
    required: true
    default: '/.+/'
  recursive:
    description: 'Whether the directory should be inspected recursively or not.'
    default: false
outputs:
  total-files-analyzed:
    description: 'The number of files analyzed.'
runs:
  using: 'node16'
  main: 'dist/index.js'
